// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: sensor_reading.proto

package sensorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SensorReadingService_GetSensors_FullMethodName    = "/SensorReadingService/GetSensors"
	SensorReadingService_GetSensorById_FullMethodName = "/SensorReadingService/GetSensorById"
)

// SensorReadingServiceClient is the client API for SensorReadingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorReadingServiceClient interface {
	GetSensors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SensorReadingResponse], error)
	GetSensorById(ctx context.Context, in *SensorReadingGetByIdRequest, opts ...grpc.CallOption) (*SensorReadingResponse, error)
}

type sensorReadingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorReadingServiceClient(cc grpc.ClientConnInterface) SensorReadingServiceClient {
	return &sensorReadingServiceClient{cc}
}

func (c *sensorReadingServiceClient) GetSensors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SensorReadingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SensorReadingService_ServiceDesc.Streams[0], SensorReadingService_GetSensors_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, SensorReadingResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorReadingService_GetSensorsClient = grpc.ServerStreamingClient[SensorReadingResponse]

func (c *sensorReadingServiceClient) GetSensorById(ctx context.Context, in *SensorReadingGetByIdRequest, opts ...grpc.CallOption) (*SensorReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorReadingResponse)
	err := c.cc.Invoke(ctx, SensorReadingService_GetSensorById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorReadingServiceServer is the server API for SensorReadingService service.
// All implementations must embed UnimplementedSensorReadingServiceServer
// for forward compatibility.
type SensorReadingServiceServer interface {
	GetSensors(*emptypb.Empty, grpc.ServerStreamingServer[SensorReadingResponse]) error
	GetSensorById(context.Context, *SensorReadingGetByIdRequest) (*SensorReadingResponse, error)
	mustEmbedUnimplementedSensorReadingServiceServer()
}

// UnimplementedSensorReadingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorReadingServiceServer struct{}

func (UnimplementedSensorReadingServiceServer) GetSensors(*emptypb.Empty, grpc.ServerStreamingServer[SensorReadingResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetSensors not implemented")
}
func (UnimplementedSensorReadingServiceServer) GetSensorById(context.Context, *SensorReadingGetByIdRequest) (*SensorReadingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSensorById not implemented")
}
func (UnimplementedSensorReadingServiceServer) mustEmbedUnimplementedSensorReadingServiceServer() {}
func (UnimplementedSensorReadingServiceServer) testEmbeddedByValue()                              {}

// UnsafeSensorReadingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorReadingServiceServer will
// result in compilation errors.
type UnsafeSensorReadingServiceServer interface {
	mustEmbedUnimplementedSensorReadingServiceServer()
}

func RegisterSensorReadingServiceServer(s grpc.ServiceRegistrar, srv SensorReadingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSensorReadingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SensorReadingService_ServiceDesc, srv)
}

func _SensorReadingService_GetSensors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SensorReadingServiceServer).GetSensors(m, &grpc.GenericServerStream[emptypb.Empty, SensorReadingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorReadingService_GetSensorsServer = grpc.ServerStreamingServer[SensorReadingResponse]

func _SensorReadingService_GetSensorById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorReadingGetByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorReadingServiceServer).GetSensorById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorReadingService_GetSensorById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorReadingServiceServer).GetSensorById(ctx, req.(*SensorReadingGetByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorReadingService_ServiceDesc is the grpc.ServiceDesc for SensorReadingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorReadingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SensorReadingService",
	HandlerType: (*SensorReadingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSensorById",
			Handler:    _SensorReadingService_GetSensorById_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSensors",
			Handler:       _SensorReadingService_GetSensors_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sensor_reading.proto",
}
