// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: sensor_reading.proto

package sensorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorReadingData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UsedKw              float64                `protobuf:"fixed64,1,opt,name=usedKw,proto3" json:"usedKw,omitempty"`
	GeneratedKw         float64                `protobuf:"fixed64,2,opt,name=generatedKw,proto3" json:"generatedKw,omitempty"`
	Time                int64                  `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Temperature         float32                `protobuf:"fixed32,4,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity            float32                `protobuf:"fixed32,5,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Pressure            float32                `protobuf:"fixed32,6,opt,name=pressure,proto3" json:"pressure,omitempty"`
	ApparentTemperature float32                `protobuf:"fixed32,7,opt,name=apparentTemperature,proto3" json:"apparentTemperature,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SensorReadingData) Reset() {
	*x = SensorReadingData{}
	mi := &file_sensor_reading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReadingData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReadingData) ProtoMessage() {}

func (x *SensorReadingData) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_reading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReadingData.ProtoReflect.Descriptor instead.
func (*SensorReadingData) Descriptor() ([]byte, []int) {
	return file_sensor_reading_proto_rawDescGZIP(), []int{0}
}

func (x *SensorReadingData) GetUsedKw() float64 {
	if x != nil {
		return x.UsedKw
	}
	return 0
}

func (x *SensorReadingData) GetGeneratedKw() float64 {
	if x != nil {
		return x.GeneratedKw
	}
	return 0
}

func (x *SensorReadingData) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SensorReadingData) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SensorReadingData) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *SensorReadingData) GetPressure() float32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *SensorReadingData) GetApparentTemperature() float32 {
	if x != nil {
		return x.ApparentTemperature
	}
	return 0
}

type SensorReadingId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorReadingId) Reset() {
	*x = SensorReadingId{}
	mi := &file_sensor_reading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReadingId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReadingId) ProtoMessage() {}

func (x *SensorReadingId) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_reading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReadingId.ProtoReflect.Descriptor instead.
func (*SensorReadingId) Descriptor() ([]byte, []int) {
	return file_sensor_reading_proto_rawDescGZIP(), []int{1}
}

func (x *SensorReadingId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,1,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber    int32                  `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_sensor_reading_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_reading_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_sensor_reading_proto_rawDescGZIP(), []int{2}
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type PaginationSensorReadingResponse struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	Items           []*SensorReadingResponse `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	PageSize        int32                    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	PageNumber      int32                    `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	HasPreviousPage bool                     `protobuf:"varint,4,opt,name=hasPreviousPage,proto3" json:"hasPreviousPage,omitempty"`
	HasNextPage     bool                     `protobuf:"varint,5,opt,name=hasNextPage,proto3" json:"hasNextPage,omitempty"`
	TotalItems      int32                    `protobuf:"varint,6,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PaginationSensorReadingResponse) Reset() {
	*x = PaginationSensorReadingResponse{}
	mi := &file_sensor_reading_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationSensorReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationSensorReadingResponse) ProtoMessage() {}

func (x *PaginationSensorReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_reading_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationSensorReadingResponse.ProtoReflect.Descriptor instead.
func (*PaginationSensorReadingResponse) Descriptor() ([]byte, []int) {
	return file_sensor_reading_proto_rawDescGZIP(), []int{3}
}

func (x *PaginationSensorReadingResponse) GetItems() []*SensorReadingResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *PaginationSensorReadingResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PaginationSensorReadingResponse) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *PaginationSensorReadingResponse) GetHasPreviousPage() bool {
	if x != nil {
		return x.HasPreviousPage
	}
	return false
}

func (x *PaginationSensorReadingResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *PaginationSensorReadingResponse) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

type CreateSensorReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *SensorReadingData     `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSensorReadingRequest) Reset() {
	*x = CreateSensorReadingRequest{}
	mi := &file_sensor_reading_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSensorReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSensorReadingRequest) ProtoMessage() {}

func (x *CreateSensorReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_reading_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSensorReadingRequest.ProtoReflect.Descriptor instead.
func (*CreateSensorReadingRequest) Descriptor() ([]byte, []int) {
	return file_sensor_reading_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSensorReadingRequest) GetData() *SensorReadingData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateSensorReadingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *SensorReadingData     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSensorReadingRequest) Reset() {
	*x = UpdateSensorReadingRequest{}
	mi := &file_sensor_reading_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSensorReadingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSensorReadingRequest) ProtoMessage() {}

func (x *UpdateSensorReadingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_reading_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSensorReadingRequest.ProtoReflect.Descriptor instead.
func (*UpdateSensorReadingRequest) Descriptor() ([]byte, []int) {
	return file_sensor_reading_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateSensorReadingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSensorReadingRequest) GetData() *SensorReadingData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SensorReadingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          *SensorReadingData     `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorReadingResponse) Reset() {
	*x = SensorReadingResponse{}
	mi := &file_sensor_reading_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReadingResponse) ProtoMessage() {}

func (x *SensorReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_reading_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReadingResponse.ProtoReflect.Descriptor instead.
func (*SensorReadingResponse) Descriptor() ([]byte, []int) {
	return file_sensor_reading_proto_rawDescGZIP(), []int{6}
}

func (x *SensorReadingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SensorReadingResponse) GetData() *SensorReadingData {
	if x != nil {
		return x.Data
	}
	return nil
}

type TimeRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         int64                  `protobuf:"varint,1,opt,name=start,proto3" json:"start,omitempty"`
	End           int64                  `protobuf:"varint,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRangeRequest) Reset() {
	*x = TimeRangeRequest{}
	mi := &file_sensor_reading_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRangeRequest) ProtoMessage() {}

func (x *TimeRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_reading_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRangeRequest.ProtoReflect.Descriptor instead.
func (*TimeRangeRequest) Descriptor() ([]byte, []int) {
	return file_sensor_reading_proto_rawDescGZIP(), []int{7}
}

func (x *TimeRangeRequest) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TimeRangeRequest) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

type NumericAggregationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericAggregationResponse) Reset() {
	*x = NumericAggregationResponse{}
	mi := &file_sensor_reading_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericAggregationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericAggregationResponse) ProtoMessage() {}

func (x *NumericAggregationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sensor_reading_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericAggregationResponse.ProtoReflect.Descriptor instead.
func (*NumericAggregationResponse) Descriptor() ([]byte, []int) {
	return file_sensor_reading_proto_rawDescGZIP(), []int{8}
}

func (x *NumericAggregationResponse) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_sensor_reading_proto protoreflect.FileDescriptor

const file_sensor_reading_proto_rawDesc = "" +
	"\n" +
	"\x14sensor_reading.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xed\x01\n" +
	"\x11SensorReadingData\x12\x16\n" +
	"\x06usedKw\x18\x01 \x01(\x01R\x06usedKw\x12 \n" +
	"\vgeneratedKw\x18\x02 \x01(\x01R\vgeneratedKw\x12\x12\n" +
	"\x04time\x18\x03 \x01(\x03R\x04time\x12 \n" +
	"\vtemperature\x18\x04 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x05 \x01(\x02R\bhumidity\x12\x1a\n" +
	"\bpressure\x18\x06 \x01(\x02R\bpressure\x120\n" +
	"\x13apparentTemperature\x18\a \x01(\x02R\x13apparentTemperature\"!\n" +
	"\x0fSensorReadingId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x11PaginationRequest\x12\x1a\n" +
	"\bpageSize\x18\x01 \x01(\x05R\bpageSize\x12\x1e\n" +
	"\n" +
	"pageNumber\x18\x02 \x01(\x05R\n" +
	"pageNumber\"\xf7\x01\n" +
	"\x1fPaginationSensorReadingResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.SensorReadingResponseR\x05items\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x05R\bpageSize\x12\x1e\n" +
	"\n" +
	"pageNumber\x18\x03 \x01(\x05R\n" +
	"pageNumber\x12(\n" +
	"\x0fhasPreviousPage\x18\x04 \x01(\bR\x0fhasPreviousPage\x12 \n" +
	"\vhasNextPage\x18\x05 \x01(\bR\vhasNextPage\x12\x1e\n" +
	"\n" +
	"totalItems\x18\x06 \x01(\x05R\n" +
	"totalItems\"D\n" +
	"\x1aCreateSensorReadingRequest\x12&\n" +
	"\x04data\x18\x01 \x01(\v2\x12.SensorReadingDataR\x04data\"T\n" +
	"\x1aUpdateSensorReadingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04data\x18\x02 \x01(\v2\x12.SensorReadingDataR\x04data\"O\n" +
	"\x15SensorReadingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12&\n" +
	"\x04data\x18\x02 \x01(\v2\x12.SensorReadingDataR\x04data\":\n" +
	"\x10TimeRangeRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x02 \x01(\x03R\x03end\"2\n" +
	"\x1aNumericAggregationResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value2\xe7\x04\n" +
	"\x14SensorReadingService\x12B\n" +
	"\n" +
	"GetSensors\x12\x12.PaginationRequest\x1a .PaginationSensorReadingResponse\x129\n" +
	"\rGetSensorById\x12\x10.SensorReadingId\x1a\x16.SensorReadingResponse\x12C\n" +
	"\fCreateSensor\x12\x1b.CreateSensorReadingRequest\x1a\x16.SensorReadingResponse\x12C\n" +
	"\fUpdateSensor\x12\x1b.UpdateSensorReadingRequest\x1a\x16.SensorReadingResponse\x128\n" +
	"\fDeleteSensor\x12\x10.SensorReadingId\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x13GetSensorByMinUsage\x12\x11.TimeRangeRequest\x1a\x16.SensorReadingResponse\x12@\n" +
	"\x13GetSensorByMaxUsage\x12\x11.TimeRangeRequest\x1a\x16.SensorReadingResponse\x12C\n" +
	"\x11GetSensorUsageAvg\x12\x11.TimeRangeRequest\x1a\x1b.NumericAggregationResponse\x12C\n" +
	"\x11GetSensorUsageSum\x12\x11.TimeRangeRequest\x1a\x1b.NumericAggregationResponseB&Z$data-manager/internal/proto;sensorpbb\x06proto3"

var (
	file_sensor_reading_proto_rawDescOnce sync.Once
	file_sensor_reading_proto_rawDescData []byte
)

func file_sensor_reading_proto_rawDescGZIP() []byte {
	file_sensor_reading_proto_rawDescOnce.Do(func() {
		file_sensor_reading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sensor_reading_proto_rawDesc), len(file_sensor_reading_proto_rawDesc)))
	})
	return file_sensor_reading_proto_rawDescData
}

var file_sensor_reading_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_sensor_reading_proto_goTypes = []any{
	(*SensorReadingData)(nil),               // 0: SensorReadingData
	(*SensorReadingId)(nil),                 // 1: SensorReadingId
	(*PaginationRequest)(nil),               // 2: PaginationRequest
	(*PaginationSensorReadingResponse)(nil), // 3: PaginationSensorReadingResponse
	(*CreateSensorReadingRequest)(nil),      // 4: CreateSensorReadingRequest
	(*UpdateSensorReadingRequest)(nil),      // 5: UpdateSensorReadingRequest
	(*SensorReadingResponse)(nil),           // 6: SensorReadingResponse
	(*TimeRangeRequest)(nil),                // 7: TimeRangeRequest
	(*NumericAggregationResponse)(nil),      // 8: NumericAggregationResponse
	(*emptypb.Empty)(nil),                   // 9: google.protobuf.Empty
}
var file_sensor_reading_proto_depIdxs = []int32{
	6,  // 0: PaginationSensorReadingResponse.items:type_name -> SensorReadingResponse
	0,  // 1: CreateSensorReadingRequest.data:type_name -> SensorReadingData
	0,  // 2: UpdateSensorReadingRequest.data:type_name -> SensorReadingData
	0,  // 3: SensorReadingResponse.data:type_name -> SensorReadingData
	2,  // 4: SensorReadingService.GetSensors:input_type -> PaginationRequest
	1,  // 5: SensorReadingService.GetSensorById:input_type -> SensorReadingId
	4,  // 6: SensorReadingService.CreateSensor:input_type -> CreateSensorReadingRequest
	5,  // 7: SensorReadingService.UpdateSensor:input_type -> UpdateSensorReadingRequest
	1,  // 8: SensorReadingService.DeleteSensor:input_type -> SensorReadingId
	7,  // 9: SensorReadingService.GetSensorByMinUsage:input_type -> TimeRangeRequest
	7,  // 10: SensorReadingService.GetSensorByMaxUsage:input_type -> TimeRangeRequest
	7,  // 11: SensorReadingService.GetSensorUsageAvg:input_type -> TimeRangeRequest
	7,  // 12: SensorReadingService.GetSensorUsageSum:input_type -> TimeRangeRequest
	3,  // 13: SensorReadingService.GetSensors:output_type -> PaginationSensorReadingResponse
	6,  // 14: SensorReadingService.GetSensorById:output_type -> SensorReadingResponse
	6,  // 15: SensorReadingService.CreateSensor:output_type -> SensorReadingResponse
	6,  // 16: SensorReadingService.UpdateSensor:output_type -> SensorReadingResponse
	9,  // 17: SensorReadingService.DeleteSensor:output_type -> google.protobuf.Empty
	6,  // 18: SensorReadingService.GetSensorByMinUsage:output_type -> SensorReadingResponse
	6,  // 19: SensorReadingService.GetSensorByMaxUsage:output_type -> SensorReadingResponse
	8,  // 20: SensorReadingService.GetSensorUsageAvg:output_type -> NumericAggregationResponse
	8,  // 21: SensorReadingService.GetSensorUsageSum:output_type -> NumericAggregationResponse
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_sensor_reading_proto_init() }
func file_sensor_reading_proto_init() {
	if File_sensor_reading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sensor_reading_proto_rawDesc), len(file_sensor_reading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sensor_reading_proto_goTypes,
		DependencyIndexes: file_sensor_reading_proto_depIdxs,
		MessageInfos:      file_sensor_reading_proto_msgTypes,
	}.Build()
	File_sensor_reading_proto = out.File
	file_sensor_reading_proto_goTypes = nil
	file_sensor_reading_proto_depIdxs = nil
}
