// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: sensor_reading.proto

package sensorpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SensorReadingService_GetSensors_FullMethodName          = "/SensorReadingService/GetSensors"
	SensorReadingService_GetSensorById_FullMethodName       = "/SensorReadingService/GetSensorById"
	SensorReadingService_CreateSensor_FullMethodName        = "/SensorReadingService/CreateSensor"
	SensorReadingService_UpdateSensor_FullMethodName        = "/SensorReadingService/UpdateSensor"
	SensorReadingService_DeleteSensor_FullMethodName        = "/SensorReadingService/DeleteSensor"
	SensorReadingService_GetSensorByMinUsage_FullMethodName = "/SensorReadingService/GetSensorByMinUsage"
	SensorReadingService_GetSensorByMaxUsage_FullMethodName = "/SensorReadingService/GetSensorByMaxUsage"
	SensorReadingService_GetSensorUsageAvg_FullMethodName   = "/SensorReadingService/GetSensorUsageAvg"
	SensorReadingService_GetSensorUsageSum_FullMethodName   = "/SensorReadingService/GetSensorUsageSum"
)

// SensorReadingServiceClient is the client API for SensorReadingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorReadingServiceClient interface {
	// CRUD
	GetSensors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SensorReadingResponse], error)
	GetSensorById(ctx context.Context, in *SensorReadingId, opts ...grpc.CallOption) (*SensorReadingResponse, error)
	CreateSensor(ctx context.Context, in *CreateSensorReadingRequest, opts ...grpc.CallOption) (*SensorReadingResponse, error)
	UpdateSensor(ctx context.Context, in *UpdateSensorReadingRequest, opts ...grpc.CallOption) (*SensorReadingResponse, error)
	DeleteSensor(ctx context.Context, in *SensorReadingId, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Aggregation
	GetSensorByMinUsage(ctx context.Context, in *TimeRangeRequest, opts ...grpc.CallOption) (*SensorReadingResponse, error)
	GetSensorByMaxUsage(ctx context.Context, in *TimeRangeRequest, opts ...grpc.CallOption) (*SensorReadingResponse, error)
	GetSensorUsageAvg(ctx context.Context, in *TimeRangeRequest, opts ...grpc.CallOption) (*NumericAggregationResponse, error)
	GetSensorUsageSum(ctx context.Context, in *TimeRangeRequest, opts ...grpc.CallOption) (*NumericAggregationResponse, error)
}

type sensorReadingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorReadingServiceClient(cc grpc.ClientConnInterface) SensorReadingServiceClient {
	return &sensorReadingServiceClient{cc}
}

func (c *sensorReadingServiceClient) GetSensors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SensorReadingResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SensorReadingService_ServiceDesc.Streams[0], SensorReadingService_GetSensors_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, SensorReadingResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorReadingService_GetSensorsClient = grpc.ServerStreamingClient[SensorReadingResponse]

func (c *sensorReadingServiceClient) GetSensorById(ctx context.Context, in *SensorReadingId, opts ...grpc.CallOption) (*SensorReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorReadingResponse)
	err := c.cc.Invoke(ctx, SensorReadingService_GetSensorById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorReadingServiceClient) CreateSensor(ctx context.Context, in *CreateSensorReadingRequest, opts ...grpc.CallOption) (*SensorReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorReadingResponse)
	err := c.cc.Invoke(ctx, SensorReadingService_CreateSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorReadingServiceClient) UpdateSensor(ctx context.Context, in *UpdateSensorReadingRequest, opts ...grpc.CallOption) (*SensorReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorReadingResponse)
	err := c.cc.Invoke(ctx, SensorReadingService_UpdateSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorReadingServiceClient) DeleteSensor(ctx context.Context, in *SensorReadingId, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SensorReadingService_DeleteSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorReadingServiceClient) GetSensorByMinUsage(ctx context.Context, in *TimeRangeRequest, opts ...grpc.CallOption) (*SensorReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorReadingResponse)
	err := c.cc.Invoke(ctx, SensorReadingService_GetSensorByMinUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorReadingServiceClient) GetSensorByMaxUsage(ctx context.Context, in *TimeRangeRequest, opts ...grpc.CallOption) (*SensorReadingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SensorReadingResponse)
	err := c.cc.Invoke(ctx, SensorReadingService_GetSensorByMaxUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorReadingServiceClient) GetSensorUsageAvg(ctx context.Context, in *TimeRangeRequest, opts ...grpc.CallOption) (*NumericAggregationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NumericAggregationResponse)
	err := c.cc.Invoke(ctx, SensorReadingService_GetSensorUsageAvg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorReadingServiceClient) GetSensorUsageSum(ctx context.Context, in *TimeRangeRequest, opts ...grpc.CallOption) (*NumericAggregationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NumericAggregationResponse)
	err := c.cc.Invoke(ctx, SensorReadingService_GetSensorUsageSum_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorReadingServiceServer is the server API for SensorReadingService service.
// All implementations must embed UnimplementedSensorReadingServiceServer
// for forward compatibility.
type SensorReadingServiceServer interface {
	// CRUD
	GetSensors(*emptypb.Empty, grpc.ServerStreamingServer[SensorReadingResponse]) error
	GetSensorById(context.Context, *SensorReadingId) (*SensorReadingResponse, error)
	CreateSensor(context.Context, *CreateSensorReadingRequest) (*SensorReadingResponse, error)
	UpdateSensor(context.Context, *UpdateSensorReadingRequest) (*SensorReadingResponse, error)
	DeleteSensor(context.Context, *SensorReadingId) (*emptypb.Empty, error)
	// Aggregation
	GetSensorByMinUsage(context.Context, *TimeRangeRequest) (*SensorReadingResponse, error)
	GetSensorByMaxUsage(context.Context, *TimeRangeRequest) (*SensorReadingResponse, error)
	GetSensorUsageAvg(context.Context, *TimeRangeRequest) (*NumericAggregationResponse, error)
	GetSensorUsageSum(context.Context, *TimeRangeRequest) (*NumericAggregationResponse, error)
	mustEmbedUnimplementedSensorReadingServiceServer()
}

// UnimplementedSensorReadingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSensorReadingServiceServer struct{}

func (UnimplementedSensorReadingServiceServer) GetSensors(*emptypb.Empty, grpc.ServerStreamingServer[SensorReadingResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetSensors not implemented")
}
func (UnimplementedSensorReadingServiceServer) GetSensorById(context.Context, *SensorReadingId) (*SensorReadingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSensorById not implemented")
}
func (UnimplementedSensorReadingServiceServer) CreateSensor(context.Context, *CreateSensorReadingRequest) (*SensorReadingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSensor not implemented")
}
func (UnimplementedSensorReadingServiceServer) UpdateSensor(context.Context, *UpdateSensorReadingRequest) (*SensorReadingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSensor not implemented")
}
func (UnimplementedSensorReadingServiceServer) DeleteSensor(context.Context, *SensorReadingId) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSensor not implemented")
}
func (UnimplementedSensorReadingServiceServer) GetSensorByMinUsage(context.Context, *TimeRangeRequest) (*SensorReadingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSensorByMinUsage not implemented")
}
func (UnimplementedSensorReadingServiceServer) GetSensorByMaxUsage(context.Context, *TimeRangeRequest) (*SensorReadingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSensorByMaxUsage not implemented")
}
func (UnimplementedSensorReadingServiceServer) GetSensorUsageAvg(context.Context, *TimeRangeRequest) (*NumericAggregationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSensorUsageAvg not implemented")
}
func (UnimplementedSensorReadingServiceServer) GetSensorUsageSum(context.Context, *TimeRangeRequest) (*NumericAggregationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSensorUsageSum not implemented")
}
func (UnimplementedSensorReadingServiceServer) mustEmbedUnimplementedSensorReadingServiceServer() {}
func (UnimplementedSensorReadingServiceServer) testEmbeddedByValue()                              {}

// UnsafeSensorReadingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorReadingServiceServer will
// result in compilation errors.
type UnsafeSensorReadingServiceServer interface {
	mustEmbedUnimplementedSensorReadingServiceServer()
}

func RegisterSensorReadingServiceServer(s grpc.ServiceRegistrar, srv SensorReadingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSensorReadingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SensorReadingService_ServiceDesc, srv)
}

func _SensorReadingService_GetSensors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SensorReadingServiceServer).GetSensors(m, &grpc.GenericServerStream[emptypb.Empty, SensorReadingResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SensorReadingService_GetSensorsServer = grpc.ServerStreamingServer[SensorReadingResponse]

func _SensorReadingService_GetSensorById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorReadingId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorReadingServiceServer).GetSensorById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorReadingService_GetSensorById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorReadingServiceServer).GetSensorById(ctx, req.(*SensorReadingId))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorReadingService_CreateSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSensorReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorReadingServiceServer).CreateSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorReadingService_CreateSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorReadingServiceServer).CreateSensor(ctx, req.(*CreateSensorReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorReadingService_UpdateSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSensorReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorReadingServiceServer).UpdateSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorReadingService_UpdateSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorReadingServiceServer).UpdateSensor(ctx, req.(*UpdateSensorReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorReadingService_DeleteSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorReadingId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorReadingServiceServer).DeleteSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorReadingService_DeleteSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorReadingServiceServer).DeleteSensor(ctx, req.(*SensorReadingId))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorReadingService_GetSensorByMinUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorReadingServiceServer).GetSensorByMinUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorReadingService_GetSensorByMinUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorReadingServiceServer).GetSensorByMinUsage(ctx, req.(*TimeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorReadingService_GetSensorByMaxUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorReadingServiceServer).GetSensorByMaxUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorReadingService_GetSensorByMaxUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorReadingServiceServer).GetSensorByMaxUsage(ctx, req.(*TimeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorReadingService_GetSensorUsageAvg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorReadingServiceServer).GetSensorUsageAvg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorReadingService_GetSensorUsageAvg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorReadingServiceServer).GetSensorUsageAvg(ctx, req.(*TimeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorReadingService_GetSensorUsageSum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorReadingServiceServer).GetSensorUsageSum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorReadingService_GetSensorUsageSum_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorReadingServiceServer).GetSensorUsageSum(ctx, req.(*TimeRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorReadingService_ServiceDesc is the grpc.ServiceDesc for SensorReadingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorReadingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SensorReadingService",
	HandlerType: (*SensorReadingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSensorById",
			Handler:    _SensorReadingService_GetSensorById_Handler,
		},
		{
			MethodName: "CreateSensor",
			Handler:    _SensorReadingService_CreateSensor_Handler,
		},
		{
			MethodName: "UpdateSensor",
			Handler:    _SensorReadingService_UpdateSensor_Handler,
		},
		{
			MethodName: "DeleteSensor",
			Handler:    _SensorReadingService_DeleteSensor_Handler,
		},
		{
			MethodName: "GetSensorByMinUsage",
			Handler:    _SensorReadingService_GetSensorByMinUsage_Handler,
		},
		{
			MethodName: "GetSensorByMaxUsage",
			Handler:    _SensorReadingService_GetSensorByMaxUsage_Handler,
		},
		{
			MethodName: "GetSensorUsageAvg",
			Handler:    _SensorReadingService_GetSensorUsageAvg_Handler,
		},
		{
			MethodName: "GetSensorUsageSum",
			Handler:    _SensorReadingService_GetSensorUsageSum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSensors",
			Handler:       _SensorReadingService_GetSensors_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sensor_reading.proto",
}
