// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/proto/sensor_reading.proto

package sensorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorReadingGetByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorReadingGetByIdRequest) Reset() {
	*x = SensorReadingGetByIdRequest{}
	mi := &file_internal_proto_sensor_reading_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReadingGetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReadingGetByIdRequest) ProtoMessage() {}

func (x *SensorReadingGetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sensor_reading_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReadingGetByIdRequest.ProtoReflect.Descriptor instead.
func (*SensorReadingGetByIdRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_sensor_reading_proto_rawDescGZIP(), []int{0}
}

func (x *SensorReadingGetByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SensorReadingResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UsedKw              float64                `protobuf:"fixed64,2,opt,name=usedKw,proto3" json:"usedKw,omitempty"`
	GeneratedKw         float64                `protobuf:"fixed64,3,opt,name=generatedKw,proto3" json:"generatedKw,omitempty"`
	Time                int64                  `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	Temperature         float32                `protobuf:"fixed32,5,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity            float32                `protobuf:"fixed32,6,opt,name=humidity,proto3" json:"humidity,omitempty"`
	Pressure            float32                `protobuf:"fixed32,7,opt,name=pressure,proto3" json:"pressure,omitempty"`
	ApparentTemperature float32                `protobuf:"fixed32,8,opt,name=apparentTemperature,proto3" json:"apparentTemperature,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SensorReadingResponse) Reset() {
	*x = SensorReadingResponse{}
	mi := &file_internal_proto_sensor_reading_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReadingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReadingResponse) ProtoMessage() {}

func (x *SensorReadingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_sensor_reading_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReadingResponse.ProtoReflect.Descriptor instead.
func (*SensorReadingResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_sensor_reading_proto_rawDescGZIP(), []int{1}
}

func (x *SensorReadingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SensorReadingResponse) GetUsedKw() float64 {
	if x != nil {
		return x.UsedKw
	}
	return 0
}

func (x *SensorReadingResponse) GetGeneratedKw() float64 {
	if x != nil {
		return x.GeneratedKw
	}
	return 0
}

func (x *SensorReadingResponse) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SensorReadingResponse) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SensorReadingResponse) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *SensorReadingResponse) GetPressure() float32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *SensorReadingResponse) GetApparentTemperature() float32 {
	if x != nil {
		return x.ApparentTemperature
	}
	return 0
}

var File_internal_proto_sensor_reading_proto protoreflect.FileDescriptor

const file_internal_proto_sensor_reading_proto_rawDesc = "" +
	"\n" +
	"#internal/proto/sensor_reading.proto\x1a\x1bgoogle/protobuf/empty.proto\"-\n" +
	"\x1bSensorReadingGetByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x81\x02\n" +
	"\x15SensorReadingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06usedKw\x18\x02 \x01(\x01R\x06usedKw\x12 \n" +
	"\vgeneratedKw\x18\x03 \x01(\x01R\vgeneratedKw\x12\x12\n" +
	"\x04time\x18\x04 \x01(\x03R\x04time\x12 \n" +
	"\vtemperature\x18\x05 \x01(\x02R\vtemperature\x12\x1a\n" +
	"\bhumidity\x18\x06 \x01(\x02R\bhumidity\x12\x1a\n" +
	"\bpressure\x18\a \x01(\x02R\bpressure\x120\n" +
	"\x13apparentTemperature\x18\b \x01(\x02R\x13apparentTemperature2\x9d\x01\n" +
	"\x14SensorReadingService\x12>\n" +
	"\n" +
	"GetSensors\x12\x16.google.protobuf.Empty\x1a\x16.SensorReadingResponse0\x01\x12E\n" +
	"\rGetSensorById\x12\x1c.SensorReadingGetByIdRequest\x1a\x16.SensorReadingResponseB\x19Z\x17internal/proto;sensorpbb\x06proto3"

var (
	file_internal_proto_sensor_reading_proto_rawDescOnce sync.Once
	file_internal_proto_sensor_reading_proto_rawDescData []byte
)

func file_internal_proto_sensor_reading_proto_rawDescGZIP() []byte {
	file_internal_proto_sensor_reading_proto_rawDescOnce.Do(func() {
		file_internal_proto_sensor_reading_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_sensor_reading_proto_rawDesc), len(file_internal_proto_sensor_reading_proto_rawDesc)))
	})
	return file_internal_proto_sensor_reading_proto_rawDescData
}

var file_internal_proto_sensor_reading_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_sensor_reading_proto_goTypes = []any{
	(*SensorReadingGetByIdRequest)(nil), // 0: SensorReadingGetByIdRequest
	(*SensorReadingResponse)(nil),       // 1: SensorReadingResponse
	(*emptypb.Empty)(nil),               // 2: google.protobuf.Empty
}
var file_internal_proto_sensor_reading_proto_depIdxs = []int32{
	2, // 0: SensorReadingService.GetSensors:input_type -> google.protobuf.Empty
	0, // 1: SensorReadingService.GetSensorById:input_type -> SensorReadingGetByIdRequest
	1, // 2: SensorReadingService.GetSensors:output_type -> SensorReadingResponse
	1, // 3: SensorReadingService.GetSensorById:output_type -> SensorReadingResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_sensor_reading_proto_init() }
func file_internal_proto_sensor_reading_proto_init() {
	if File_internal_proto_sensor_reading_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_sensor_reading_proto_rawDesc), len(file_internal_proto_sensor_reading_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_sensor_reading_proto_goTypes,
		DependencyIndexes: file_internal_proto_sensor_reading_proto_depIdxs,
		MessageInfos:      file_internal_proto_sensor_reading_proto_msgTypes,
	}.Build()
	File_internal_proto_sensor_reading_proto = out.File
	file_internal_proto_sensor_reading_proto_goTypes = nil
	file_internal_proto_sensor_reading_proto_depIdxs = nil
}
